version: '3.8'
services:
  db:
    container_name: pg_container_vectore
    image: ankane/pgvector
    restart: always
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: test_db
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data
    networks:
      - crawler_network

  rabbitmq:
    image: rabbitmq:3.12-management
    container_name: crawler_rabbitmq
    hostname: rabbitmq
    ports:
      - "5672:5672"    # AMQP port
      - "15672:15672"  # Management UI port
    environment:
      RABBITMQ_ERLANG_COOKIE: supersecretcookievalue123
      RABBITMQ_DEFAULT_USER: crawler_user
      RABBITMQ_DEFAULT_PASS: crawler_pass
      RABBITMQ_DEFAULT_VHOST: crawler_vhost
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    networks:
      - crawler_network

  ollama:
    image: ollama/ollama
    container_name: crawler_ollama
    restart: always
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama
    networks:
      - crawler_network

  ollama_setup:
    image: appropriate/curl
    container_name: ollama_setup
    depends_on:
      - ollama
    networks:
      - crawler_network
    volumes:
      - ./ollama_setup.sh:/ollama_setup.sh
    command: ["sh", "/ollama_setup.sh"]

volumes:
  pg_data:
  rabbitmq_data:
  ollama_data:

networks:
  crawler_network:
    driver: bridge
