"""add file_type and embedding_type to web_pages

Revision ID: 5027f84c0e0f
Revises: 8c370d6d0e91
Create Date: 2025-08-08 17:14:31.340520

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "5027f84c0e0f"
down_revision: Union[str, Sequence[str], None] = "8c370d6d0e91"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("web_pages", sa.Column("file_type", sa.String(), nullable=False, server_default='html'))
    op.add_column("web_pages", sa.Column("embedding_type", sa.String(), nullable=False, server_default='text'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("web_pages", "embedding_type")
    op.drop_column("web_pages", "file_type")
    # ### end Alembic commands ###
