"""Remove job_type from jobs table

Revision ID: 8c370d6d0e91
Revises: c90980031014
Create Date: 2025-08-03 19:02:08.578996

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8c370d6d0e91'
down_revision: Union[str, Sequence[str], None] = 'c90980031014'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('jobs', 'job_type')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('jobs', sa.Column('job_type', sa.VARCHAR(), autoincrement=False, nullable=False, server_default='scrapy'))
    # ### end Alembic commands ###
